use database data_catalogue;
use schema public;

create or replace TABLE DATA_CATALOGUE cluster by (feed_identifier, file_location)(
	FEED_IDENTIFIER VARCHAR(16777216) NOT NULL,
	FEED_VERSION NUMBER(38,0) NOT NULL,
	FILE_LOCATION VARCHAR(16777216),
	CATALOGUED_TIME TIMESTAMP_NTZ(9) NOT NULL,
	POSTED_BY VARCHAR(16777216),
	ORGANISATION VARCHAR(16777216) NOT NULL,
	FILE_HASH VARCHAR(16777216) NOT NULL,
	FILE_META VARIANT NOT NULL
);
create or replace TABLE SOURCE_MASTER cluster by (loaded_time, filename)(
	FILENAME VARCHAR(16777216),
	FILE_ROW_NUMBER NUMBER(38,0),
	LOADED_TIME TIMESTAMP_NTZ(9),
	INFORMATION VARCHAR(16777216)
);

CREATE OR REPLACE FILE FORMAT DATA_CATALOGUE_FORMAT
	SKIP_HEADER = 1
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
;
CREATE OR REPLACE FILE FORMAT MORRISONS_DATA_FORMAT
	SKIP_HEADER = 1
;