use database raw;
use schema dsr_input

create or replace TABLE INPUT_ACT_INV_LOCATIONDAYCASE cluster by (loaded_timestamp)(
	DAY_DATE DATE NOT NULL,
	SOURCE_DB_ID VARCHAR(16777216) NOT NULL,
	ORGANISATION_LOCATION_ID VARCHAR(16777216) NOT NULL,
	LOCATION_FUNCTION VARCHAR(16777216) NOT NULL,
	ORGANISATION_CASE VARCHAR(100) NOT NULL,
	STOCK_UNITS NUMBER(38,0) NOT NULL,
	STOCK_VALUE NUMBER(38,4),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL,
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_ACT_INV_LOCATIONDAYSKU cluster by (loaded_timestamp)(
	DAY_DATE DATE NOT NULL,
	SOURCE_DB_ID VARCHAR(16777216) NOT NULL,
	ORGANISATION_LOCATION_ID VARCHAR(16777216) NOT NULL,
	LOCATION_FUNCTION VARCHAR(16777216) NOT NULL,
	ORGANISATION_SKU VARCHAR(100) NOT NULL,
	STOCK_UNITS NUMBER(38,0),
	STOCK_VALUE NUMBER(38,4),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL,
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_ACT_MVT_DEPOTSTOREDAYSKU cluster by (loaded_timestamp)(
	DAY_DATE DATE,
	SOURCE_DB_ID VARCHAR(16777216),
	ORGANISATION_LOCATION_ID_FROM VARCHAR(16777216),
	ORGANISATION_LOCATION_ID_TO VARCHAR(16777216),
	ORGANISATION_SKU VARCHAR(100),
	UNITS_ORDERED NUMBER(38,0),
	UNITS_FULFILLED NUMBER(38,0),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_ACT_MVT_ORGDEPOTDAYCASE cluster by (loaded_timestamp)(
	DAY_DATE DATE,
	SOURCE_DB_ID VARCHAR(16777216),
	BUSINESS_ORGANISATION_NUMBER_FROM VARCHAR(16777216),
	ORGANISATION_LOCATION_ID VARCHAR(16777216),
	ORGANISATION_CASE VARCHAR(100),
	CASES_ORDERED_IN NUMBER(38,0),
	CASES_FULFILLED_IN NUMBER(38,0),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_ACT_MVT_STOREDAYSKU cluster by (loaded_timestamp)(
	DAY_DATE DATE,
	SOURCE_DB_ID VARCHAR(16777216),
	ORGANISATION_LOCATION_ID VARCHAR(16777216),
	ORGANISATION_SKU VARCHAR(100),
	EPOS_EACHES NUMBER(38,2),
	EPOS_VALUE NUMBER(38,2),
	RTC_EPOS_EACHES NUMBER(38,2),
	RTC_EPOS_VALUE NUMBER(38,2),
	RTC_REDUCTION_VALUE NUMBER(38,2),
	BIN_WASTE_EACHES NUMBER(38,2),
	BIN_WASTE_VALUE NUMBER(38,2),
	TOTAL_WASTE_EACHES NUMBER(38,2),
	TOTAL_WASTE_VALUE NUMBER(38,2),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL,
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_CALENDAR (
	ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	DAY_DATE DATE,
	WEEK_ID NUMBER(38,0),
	YEAR_ID NUMBER(38,0),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_CASE (
	ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	ORGANISATION_CASE VARCHAR(100),
	ORGANISATION_SKU VARCHAR(100),
	CASE_SIZE NUMBER(38,0),
	GTIN VARCHAR(250),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_CASE_GROUPING (
	SUBJECT_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	SUBJECT_BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	ORGANISATION_CASE VARCHAR(100),
	CREATOR_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	CREATOR_BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	GROUPING_KEY VARCHAR(16777216),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_DATE (
	DAY_DATE DATE NOT NULL,
	YEAR NUMBER(38,0) NOT NULL,
	MONTH NUMBER(38,0) NOT NULL,
	MONTH_NAME VARCHAR(16777216) NOT NULL,
	DAY_OF_MONTH NUMBER(38,0) NOT NULL,
	DAY_OF_WEEK VARCHAR(9) NOT NULL,
	WEEK_OF_YEAR NUMBER(38,0) NOT NULL,
	DAY_OF_YEAR NUMBER(38,0) NOT NULL,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (DAY_DATE)
);
create or replace TABLE INPUT_DELEGATED_VISIBILITY (
	DELEGATOR_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	DELEGATOR_ORGANISATION_NUMBER VARCHAR(16777216),
	DELEGATEE_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	DELEGATEE_ORGANISATION_NUMBER VARCHAR(16777216),
	SUBJECT_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	SUBJECT_ORGANISATION_NUMBER VARCHAR(16777216),
	PRODUCT_TYPE VARCHAR(100),
	ORGANISATION_PRODUCT VARCHAR(100),
	DELEGATED_STATUS BOOLEAN,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_LOCATION (
	ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	ORGANISATION_LOCATION_ID VARCHAR(16777216),
	LOCATION_FUNCTION VARCHAR(16777216),
	GEOGRAPHIC_LOCATION GEOGRAPHY,
	ATTRIBUTES VARIANT,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_LOCATION_GROUP (
	CREATOR_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	CREATOR_BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	SUBJECT_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	SUBJECT_BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	ORGANISATION_LOCATION_ID VARCHAR(16777216),
	LOCATION_FUNCTION VARCHAR(16777216),
	GROUP_NAME VARCHAR(16777216),
	LOCATION_GROUP_NAME VARCHAR(16777216),
	GROUP_VALUE VARCHAR(16777216),
	ATTRIBUTES VARIANT,
	CREATED_TIMESTAMP VARCHAR(16777216),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_LOCATION_PARENTAGE (
	SUBJECT_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	SUBJECT_BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	SUBJECT_ORGANISATION_LOCATION_ID VARCHAR(16777216),
	SUBJECT_LOCATION_FUNCTION VARCHAR(16777216),
	PARENT_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	PARENT_BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	PARENT_ORGANISATION_LOCATION_ID VARCHAR(16777216),
	PARENT_LOCATION_FUNCTION VARCHAR(16777216),
	CREATOR_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	CREATOR_BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_ORGANISATION (
	ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	ATTRIBUTES VARIANT,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_ORGANISATION_MAPPING (
	ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	BUSINESS_ORGANISATION_NAME VARCHAR(16777216),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_ORGANISATION_PARENTAGE (
	ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	PARENT_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	PARENT_BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	CREATOR_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	CREATOR_BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_PLN_INV_STOREDAYSKU cluster by (loaded_timestamp)(
	DAY_DATE DATE,
	SOURCE_DB_ID VARCHAR(16777216),
	ORGANISATION_LOCATION_ID VARCHAR(16777216),
	ORGANISATION_SKU VARCHAR(100),
	RANGED BOOLEAN,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_PLN_MVT_DAYSKU cluster by (loaded_timestamp)(
	BASE_FORECAST_DATE DATE,
	FORECAST_DATE DATE,
	SOURCE_DB_ID VARCHAR(16777216),
	SUBJECT_BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	ORGANISATION_SKU VARCHAR(100),
	UNITS_REQUIRED NUMBER(38,0),
	UNITS_REQUIRED_UPPER NUMBER(38,0),
	UNITS_REQUIRED_LOWER NUMBER(38,0),
	FORECAST_COMPONENTS OBJECT,
	CREATED_AT TIMESTAMP_NTZ(9),
	MODEL_VERSION VARCHAR(255),
	ORIGIN_FILE VARCHAR(255),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_PLN_MVT_DEPOTSTOREDAYSKU cluster by (loaded_timestamp)(
	BASE_FORECAST_DATE DATE NOT NULL,
	FORECAST_DATE DATE NOT NULL,
	SOURCE_DB_ID VARCHAR(16777216) NOT NULL,
	ORGANISATION_LOCATION_ID_FROM VARCHAR(16777216) NOT NULL,
	ORGANISATION_LOCATION_ID_TO VARCHAR(16777216) NOT NULL,
	ORGANISATION_SKU VARCHAR(100) NOT NULL,
	UNITS_REQUIRED NUMBER(38,0),
	UNITS_REQUIRED_UPPER NUMBER(38,0),
	UNITS_REQUIRED_LOWER NUMBER(38,0),
	FORECAST_COMPONENTS OBJECT,
	CREATED_AT TIMESTAMP_NTZ(9),
	MODEL_VERSION VARCHAR(255) NOT NULL,
	STATUS BOOLEAN NOT NULL,
	ORIGIN_FILE VARCHAR(255),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL,
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_PLN_MVT_ORGDEPOTDAYSKU cluster by (loaded_timestamp)(
	BASE_FORECAST_DATE DATE,
	FORECAST_DATE DATE,
	SOURCE_DB_ID VARCHAR(16777216),
	SUBJECT_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	SUBJECT_BUSINESS_ORGANISATION_NUMBER_FROM VARCHAR(16777216),
	SUBJECT_BUSINESS_ORGANISATION_NUMBER_TO VARCHAR(16777216),
	SUBJECT_ORGANISATION_SKU VARCHAR(100),
	SUBJECT_ORGANISATION_LOCATION_ID_TO VARCHAR(16777216),
	UNITS_REQUIRED NUMBER(38,0),
	UNITS_REQUIRED_UPPER NUMBER(38,0),
	UNITS_REQUIRED_LOWER NUMBER(38,0),
	CASES_REQUIRED NUMBER(38,0),
	CASES_REQUIRED_UPPER NUMBER(38,0),
	CASES_REQUIRED_LOWER NUMBER(38,0),
	FORECAST_COMPONENTS OBJECT,
	CREATED_AT TIMESTAMP_NTZ(9),
	MODEL_VERSION VARCHAR(255),
	ORIGIN_FILE VARCHAR(255),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_PLN_MVT_STOREDAYSKU cluster by (loaded_timestamp)(
	BASE_FORECAST_DATE DATE NOT NULL,
	FORECAST_DATE DATE NOT NULL,
	SOURCE_DB_ID VARCHAR(16777216) NOT NULL,
	SUBJECT_BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216) NOT NULL,
	SUBJECT_ORGANISATION_LOCATION_ID_TO VARCHAR(16777216) NOT NULL,
	ORGANISATION_SKU VARCHAR(100) NOT NULL,
	UNITS_REQUIRED NUMBER(38,0),
	UNITS_REQUIRED_UPPER NUMBER(38,0),
	UNITS_REQUIRED_LOWER NUMBER(38,0),
	FORECAST_COMPONENTS OBJECT,
	CREATED_AT TIMESTAMP_NTZ(9),
	MODEL_VERSION VARCHAR(255) NOT NULL,
	ORIGIN_FILE VARCHAR(255),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL,
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_PROMOTION (
	CREATOR_BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216) NOT NULL,
	CREATOR_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	SUBJECT_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	SUBJECT_BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216) NOT NULL,
	PROMOTION_NUMBER VARCHAR(16777216) NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	ORGANISATION_SKU VARCHAR(16777216) NOT NULL,
	ATTRIBUTES VARIANT,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL,
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_SKU (
	ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	ORGANISATION_SKU VARCHAR(100),
	DESCRIPTION VARCHAR(250),
	INDIVIDUAL_UNITS NUMBER(38,0),
	NET_QUANTITY NUMBER(38,0),
	BASE_UNIT VARCHAR(100),
	BRAND VARCHAR(250),
	GTIN VARCHAR(250),
	ATTRIBUTES VARIANT,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE INPUT_SKU_GROUPING (
	SUBJECT_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	SUBJECT_BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	ORGANISATION_SKU VARCHAR(100),
	CREATOR_ORIGIN_ORGANISATION_NUMBER VARCHAR(16777216),
	CREATOR_BUSINESS_ORGANISATION_NUMBER VARCHAR(16777216),
	GROUP_NAME VARCHAR(16777216),
	GROUP_VALUE VARCHAR(16777216),
	LOADED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL
);